### PR TITLE
Adds album covers to the search results.

### PR DESCRIPTION
**Pull request by enhorn**

### CODE REVIEW

**Comment by phpfunk** [comment]
Looking at the best way to incorporate this and testing locally. Will probably disable images by default and allow folks to turn it on in the command when they install. If turned on, the image commands will be run and for a max of 5. Wishing Spotify had artwork in their API. Would integrate so much better.

**Comment by enhorn** [comment]
Yeah, I notised that it got too slow with more than five results, downloading and parsing a full HTML page for each result really isn't that beautiful. ;-)

**Comment by phpfunk** [comment]
Hey, I pushed this live. Great addition, I really appreciate. A few things:
- I added `IMAGES="no"` to the `spot search` by default. To enable images users must change `IMAGES="no"` to `IMAGES="yes"`
- I removed the large library to parse HTML and just used a simple regex to get the og:image
- I switched the cache folder to an artwork folder within the workflow so if the user deletes the workflow they don't have to worry about finding the other cache folder
- Decreased curl timeouts from 20 seconds per call to 5
- Instead of always calling `open.spotify.com/track/KEY`, I added the ability to call `/track/`, `/artist/` and `/album/` to get relevant artwork for each search.
- Added your name to the readme as contributor and obviously gave you props for the image addition

Again, thanks this is AWESOME!

**Comment by enhorn** [comment]
Godo changes/additions! :-)

**Pull request closed without merging**
